### ISSUE TITLE
Typescript Starter: 'ERROR: ModuleBuildError'

### ISSUE THREAD

**Issue by krokerke** [cerebral/webpackbin#48]
Following error on starting an new project with typescript:

> Module build failed: Error: ts-loader was supplied with an unexpected loader option: isolatedModules
> 
> Please take a look at the options you are supplying; the following are valid options:
> silent / logLevel / logInfoToStdOut / instance / compiler / configFile / configFileName / transpileOnly / ignoreDiagnostics / visualStudioErrorFormat / compilerOptions / appendTsSuffixTo / appendTsxSuffixTo / entryFileIsJs / happyPackMode / getCustomTransformers
> 
>     at validateLoaderOptions (/app/node_modules/ts-loader/dist/index.js:92:19)
>     at getLoaderOptions (/app/node_modules/ts-loader/dist/index.js:75:5)
>     at Object.loader (/app/node_modules/ts-loader/dist/index.js:23:19)

**Comment by christianalfoni** [comment]
Hi there, sorry for late response!

Webpackbin is being refactored to latest versions of React and Cerebral, which will be out soon. Have not been able to reproduce it locally. So will make another check. This will happen during weekend :)

**Comment by jkleiser** [comment]
I got the same error just now, using Safari 11.0.1, and the same in Chrome 62.0.3202.75, on macOS.

**Comment by bbonczek** [comment]
same here

**Comment by Guria** [comment]
Check if clearing cache / cookies helps.

**Comment by bbonczek** [comment]
Tried to open in incognito mode on Chrome 61.0.3163.100 64-bit, and error still occurs.

**Comment by bbonczek** [comment]
FYI

I am not trying to create new typescript project. Instead I want to open https://www.webpackbin.com/bins/-KqGwvVQLknZ-fTXHjCO .

**Comment by krokerke** [comment]
The error is caused by the 'new' config validation in 2.3.7 of ts-loader (installed automatically when building with the current package.json).
need to fix the options in the ts-loader config, pull request is open
